sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: xxx
    access-key-id: x
    access-key-secret: sxxxx
    bucket-name: xxx
  redis:
    host: xxx
    port: xxx
    password: xxx