sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: xxx
    access-key-id: xxx
    access-key-secret: xxx
    bucket-name: xxx
  redis:
      host: xx
      port: xxx
      password: xx
  wechat:
    appid: xx
    secret: xxx
    mchid: 1600090001
    mchSerialNo: 1600090001
    privateKeyFilePath: /Users/jin/Desktop/1600090001/apiclient_key.pem
    apiV3Key: 7c0b0f0a0b0f0a0b0f0a0b0f0a0b0f0a0b0f0a0b0f0a0b0f0a0b0f0a0b0f0a0b0f0a0b0f0a0b0f0a0b0f0a0b0f0
    weChatPayCertFilePath: /Users/jin/Desktop/1600090001/apiclient_cert.pem
    notifyUrl: http://127.0.0.1:8080/api/v1/pay/notify
    refundNotifyUrl: http://127.0.0.1:8080/api/v1/pay/refundNotify